name: Publish to Nuget

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      # Setup GitVersion
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      # Generate GitVersion
      - name: Generate Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true

      # Restore
      - name: Restore
        run: dotnet restore

      # Build
      - name: Build
        run: dotnet pack -c Release /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }} -o nupkg

      # Push
      - name: Push
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: ./nupkg
